name: "Check if Exists apps"
description: "Este action valida si la aplicación existe en GitOps"

inputs:
  gitOpsUrl: 
    description: "Url de github-integration"
    required: false
    default: "https://github-integration.andreani.com"
runs:
  using: "composite"
  steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Consulta al endpoint"
        env:
          GITHUB_REPONAME: ${{ github.event.repository.name }}
          GITHUB_OWNER: ${{ github.repository_owner }}
        shell: bash 
        run: |-
          echo $GITHUB_REPONAME
          echo $GITHUB_OWNER
          status_code=$(curl -o /dev/null -s -w "%{http_code}\n" --location --head "${{ inputs.gitOpsUrl }}/api/v1/org/${{ env.GITHUB_OWNER }}/repository/${{ env.GITHUB_REPONAME }}")
          if [ "$status_code" -eq 200 ]; then
            echo "OK - The application are register in GitOps"
          elif [ "$status_code" -eq 404 ]; then
            echo "Error: The application are not register in GitOps. Send message to devops team"
            exit 1
          else
            echo "Error: The GitOps response error -> $status_code"
            exit 1
          fi

