name: "Continuos Integration Validations"
description: "Continuous Integration Validations step."

inputs:
  # Github
  github_username:
    description: "usuario de github para autenticarse en los packages"
    required: true
  github_token:
    description: "token del usuario con permisos de lectura en packages"
    required: true

runs:
  using: "composite"
  steps:
    - name: Comment on PR
      uses: actions/github-script@v4
      with:
        github-token: ${{inputs.github_token}}
        script: |
          const issue_number = context.payload.pull_request.number;
          const repo = context.repo;
          github.issues.createComment({
            ...repo,
            issue_number: issue_number,
            body: '✨ Continuos Integration Success ✨'
          });